export type Activity = {
    id: number,
    resource_state: number,
    external_id: string,
    upload_id: number,
    athlete: {
        id: number,
        resource_state: number,
    },
    name: string,
    distance: number,
    moving_time: number,
    elapsed_time: number,
    total_elevation_gain: number,
    type: string,
    start_date: string,
    start_date_local: string,
    timezone: string,
    utc_offset: number,
    start_latlng: [ number, number ],
    end_latlng: [ number, number ],
    location_city: string | null,
    location_state: string | null,
    location_country: string,
    start_latitude: number,
    start_longitude: number,
    achievement_count: number,
    kudos_count: number,
    comment_count: number,
    athlete_count: number,
    photo_count: number,
    map: {
        id: number,
        polyline: string,
        resource_state: number,
        summary_polyline: string,
    },
    trainer: boolean,
    commute: boolean,
    manual: boolean,
    private: boolean,
    flagged: boolean,
    gear_id: string,
    from_accepted_tag: boolean,
    average_speed: number,
    max_speed: number,
    average_cadence: number,
    average_temp: number,
    average_watts: number,
    weighted_average_watts: number,
    kilojoules: number,
    device_watts: boolean,
    has_heartrate: boolean,
    max_watts: number,
    elev_high: number,
    elev_low: number,
    pr_count: number,
    total_photo_count: number,
    has_kudoed: boolean,
    workout_type: number,
    suffer_score: number | null,
    description: string,
    calories: number,
    segment_efforts: Array<Object>,
    splits_metric: Array<Object>,
    laps: Array<Object>,
    gear: {
        id: string,
        primary: boolean,
        name: string,
        resource_state: number,
        distance: number,
    },
    partner_brand_tag: string | null,
    photos: Object,
    highlighted_kudosers: Array<Object>,
    device_name: string,
    embed_token: string,
    segment_leaderboard_opt_out: boolean,
    leaderboard_opt_out: boolean,
};
