/* eslint-disable typescript-sort-keys/interface */
export interface ApiActivity {
    achievement_count: number;
    athlete: {
        id: number;
        resource_state: number;
    };
    athlete_count: number;
    average_cadence: number;
    average_speed: number;
    average_temp: number;
    average_watts: number;
    calories: number;
    comment_count: number;
    commute: boolean;
    description: string;
    device_name: string;
    device_watts: boolean;
    distance: number;
    elapsed_time: number;
    elev_high: number;
    elev_low: number;
    embed_token: string;
    end_latlng: [number, number];
    external_id: string;
    flagged: boolean;
    from_accepted_tag: boolean;
    id: number;
    kudos_count: number;
    utc_offset: number;
    has_kudoed: boolean;
    highlighted_kudosers: Record<string, unknown>[];
    map: {
        id: number;
        polyline: string;
        resource_state: number;
        summary_polyline: string;
    };
    kilojoules: number;
    total_elevation_gain: number;
    laps: Record<string, unknown>[];
    private: boolean;
    start_latitude: number;
    location_country: string;
    start_longitude: number;
    manual: boolean;
    max_speed: number;
    upload_id: number;
    name: string;
    timezone: string;
    weighted_average_watts: number;
    trainer: boolean;
    photo_count: number;
    has_heartrate: boolean;
    max_watts: number;
    start_latlng: [number, number];
    location_state: string | null;
    pr_count: number;
    total_photo_count: number;
    splits_metric: Record<string, unknown>[];
    start_date: string;
    gear_id: string;
    type: string;
    moving_time: number;
    segment_efforts: Record<string, unknown>[];
    suffer_score: number | null;
    resource_state: number;
    gear: {
        distance: number;
        id: string;
        name: string;
        primary: boolean;
        resource_state: number;
    };
    partner_brand_tag: string | null;
    photos: Record<string, unknown>;
    start_date_local: string;
    workout_type: number;
    location_city: string | null;
    segment_leaderboard_opt_out: boolean;
    leaderboard_opt_out: boolean;
}
